# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build gabriel'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["swweeep_left","swweeep_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=n\nCONFIG_ZMK_POINTING=y\nCONFIG_ZMK_SLEEP=y"]'
      branches: '["default"]'
      modules: '["default"]'
